### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by elgs** [zurb/foundation-migrate#4]
Does it change and overwrite the old code? This migration plugin run in browser, how can it have write access to local files?

Thanks,
Elgs

**Comment by mrsweaters** [comment]
The plugin does change Foundation 5 to work like Foundation 4, but it also gives you helpful notifications that can guide you during your upgrade.

**Comment by elgs** [comment]
Thanks @mrsweaters, do does it mean this plugin has two functions:
1, it works as a bridge to change Foundation 5 to work like Foundation 4;
2, it gives advices in the console until all old code is migrated;

What it does not do is to modify any old code (I don't think it can.). Am I right?

Thanks,
Elgs

**Comment by mrsweaters** [comment]
Sorry I didn't see this. You are right with points one and two. It modifies the _new_ code to work like the old but not the old code to work like the new.

**Comment by elgs** [comment]
Thank you @mrsweaters.
