### ISSUE TITLE
lib_methods is undefined?

### ISSUE THREAD

**Issue by kevincolten** [zurb/foundation-migrate#5]
I am getting the error `Cannot read property 'old_bindings' of undefined` on line 5 `Foundation.lib_methods.old_bindings = Foundation.lib_methods.old_bindings || Foundation.lib_methods.bindings;`
Setting a breakpoint, Foundation is defined at this point and is version `"5.2.3"`
Any suggestions?

**Comment by yoooee** [comment]
Same here... Uncaught TypeError: Cannot read property 'old_bindings' of undefined.

**Comment by vijaykc** [comment]
any update here?
